name: "nightly build-jdk nightly"
on:
  schedule:
    - cron:  '30 21 * * 1-5'

jobs:
  hotspot:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2016]
        javaToBuild: [jdk11u, jdk15u]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/build-jdk@v1
      id: buildJDK
      with: 
        javaToBuild: ${{ matrix.javaToBuild }}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
  openj9:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
        javaToBuild: [jdk11u, jdk15u]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/build-jdk@v1
      id: buildJDK
      with: 
        javaToBuild: ${{ matrix.javaToBuild }}
        impl: 'openj9'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version