name: "nightly build-jdk nightly"
on:
  schedule:
    - cron:  '30 21 * * 1-5'

jobs:
  hotspot:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2016]
        javaToBuild: [jdk11u, jdk17u]
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: adoptium/build-jdk@2f4b8fc221a368382953dadd191d60da48a67063 # v1.0.4
      id: buildJDK
      with:
        javaToBuild: ${{ matrix.javaToBuild }}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
  openj9:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        javaToBuild: [jdk11u, jdk17u]
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: adoptium/build-jdk@2f4b8fc221a368382953dadd191d60da48a67063 # v1.0.4
      id: buildJDK
      with:
        javaToBuild: ${{ matrix.javaToBuild }}
        impl: 'openj9'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
